"""Create department table

Revision ID: 16a499647b8c
Revises: 33761a756287
Create Date: 2026-07-09 21:53:51.917995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a499647b8c'
down_revision: Union[str, Sequence[str], None] = '33761a756287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
