"""Improve database models

Revision ID: 46468cd65f89
Revises: 77cfdb0c787d
Create Date: 2026-07-07 18:32:46.669535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46468cd65f89'
down_revision: Union[str, Sequence[str], None] = '77cfdb0c787d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_department_per_institution', 'departments', ['institution_id', 'name'])
    op.add_column('institutions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('institutions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('institutions', 'website',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('uq_institution_name', 'institutions', ['name'])
    op.add_column('researchers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('researchers', sa.Column('experience', sa.String(length=100), nullable=True))
    op.add_column('researchers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('researchers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('researchers', 'orcid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('researchers', 'google_scholar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('researchers', 'research_gate',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('researchers', 'linkedin',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'researchers', ['orcid'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_user_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'researchers', type_='unique')
    op.alter_column('researchers', 'linkedin',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('researchers', 'research_gate',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('researchers', 'google_scholar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('researchers', 'orcid',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('researchers', 'updated_at')
    op.drop_column('researchers', 'created_at')
    op.drop_column('researchers', 'experience')
    op.drop_column('researchers', 'phone')
    op.drop_constraint('uq_institution_name', 'institutions', type_='unique')
    op.alter_column('institutions', 'website',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('institutions', 'updated_at')
    op.drop_column('institutions', 'created_at')
    op.drop_constraint('uq_department_per_institution', 'departments', type_='unique')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    # ### end Alembic commands ###
