const API = "http://127.0.0.1:8000";
const collaborationModal = new bootstrap.Modal(document.getElementById("collaborationModal"));
const form = document.getElementById("collaborationForm");
let records = [], researchers = [], publications = [];
const esc = value => String(value ?? "-").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

async function loadOptions(){
  [researchers, publications] = await Promise.all([fetch(`${API}/researchers/`).then(r=>r.json()), fetch(`${API}/publications/`).then(r=>r.json())]);
  const researcherOptions = `<option value="">Select a researcher</option>${researchers.map(r=>`<option value="${r.id}">${esc(r.full_name)}${r.institution_id ? ` (Institution ${r.institution_id})` : ""}</option>`).join("")}`;
  document.getElementById("researcher1Id").innerHTML = researcherOptions;
  document.getElementById("researcher2Id").innerHTML = researcherOptions;
  document.getElementById("publicationId").innerHTML = `<option value="">No related publication</option>${publications.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join("")}`;
}
async function loadCollaborations(){
  const rows=document.getElementById("collaborationRows");
  try { const response=await fetch(`${API}/collaborations/detailed`); if(!response.ok)throw new Error("Unable to load collaborations"); records=await response.json(); rows.innerHTML=records.length?records.map(item=>{const pending=item.status==='pending';const status=`<span class="badge text-bg-${pending?'warning':item.status==='accepted'?'success':'danger'}">${esc(item.status)}</span>`;const decision=pending?`<button class="btn btn-sm btn-success ms-1" onclick="decideCollaboration(${item.id},'accepted')" title="Accept"><i class="bi bi-check-lg"></i></button><button class="btn btn-sm btn-outline-danger ms-1" onclick="decideCollaboration(${item.id},'rejected')" title="Reject"><i class="bi bi-x-lg"></i></button>`:'';return `<tr><td><strong>${esc(item.researcher1_name)}</strong><small class="d-block text-muted">${esc(item.researcher1_institution)}</small></td><td><strong>${esc(item.researcher2_name)}</strong><small class="d-block text-muted">${esc(item.researcher2_institution)}</small></td><td>${esc(item.project)}</td><td>${esc(item.publication_title)}</td><td>${status}</td><td class="text-end">${decision}<button class="btn btn-sm btn-outline-primary ms-1" onclick="editCollaboration(${item.id})"><i class="bi bi-pencil"></i></button><button class="btn btn-sm btn-outline-danger ms-1" onclick="deleteCollaboration(${item.id})"><i class="bi bi-trash"></i></button></td></tr>`}).join(""):'<tr><td colspan="6" class="text-center text-muted">No collaborations created yet.</td></tr>'; } catch(error){rows.innerHTML=`<tr><td colspan="6" class="text-center text-danger">${esc(error.message)}</td></tr>`;}
}
function resetForm(){form.reset();document.getElementById("collaborationId").value="";document.getElementById("modalTitle").textContent="Add Collaboration";}
function editCollaboration(id){const item=records.find(r=>r.id===id);if(!item)return;document.getElementById("collaborationId").value=id;document.getElementById("researcher1Id").value=item.researcher1_id;document.getElementById("researcher2Id").value=item.researcher2_id;document.getElementById("project").value=item.project||"";document.getElementById("publicationId").value=item.publication_id||"";document.getElementById("modalTitle").textContent="Edit Collaboration";collaborationModal.show();}
async function deleteCollaboration(id){if(!confirm("Delete this collaboration record?"))return;const r=await fetch(`${API}/collaborations/${id}`,{method:"DELETE"});if(!r.ok){alert("Delete failed");return;}loadCollaborations();}
async function decideCollaboration(id,decision){if(!confirm(`Mark this request as ${decision}?`))return;const r=await fetch(`${API}/collaborations/${id}/decision?decision=${decision}`,{method:"POST"});if(!r.ok){alert((await r.json()).detail||"Decision failed");return;}loadCollaborations();}
form.addEventListener("submit",async event=>{event.preventDefault();const id=document.getElementById("collaborationId").value,payload={researcher1_id:Number(document.getElementById("researcher1Id").value),researcher2_id:Number(document.getElementById("researcher2Id").value),project:document.getElementById("project").value.trim()||null,publication_id:document.getElementById("publicationId").value?Number(document.getElementById("publicationId").value):null};if(payload.researcher1_id===payload.researcher2_id){alert("Choose two different researchers.");return;}const r=await fetch(`${API}/collaborations/${id||""}`,{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){alert((await r.json()).detail||"Save failed");return;}collaborationModal.hide();loadCollaborations();});
loadOptions().then(loadCollaborations).catch(()=>{document.getElementById("collaborationRows").innerHTML='<tr><td colspan="5" class="text-center text-danger">Unable to load collaboration data.</td></tr>';});
