"""add publication editorial decision

Revision ID: 26c521162e56
Revises: ab8d6c61a76b
Create Date: 2026-07-16 21:55:21.461207

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "26c521162e56"
down_revision: str | None = "ab8d6c61a76b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publications", sa.Column("editor_note", sa.Text(), nullable=True))
    op.add_column(
        "publications", sa.Column("decision_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("publications", sa.Column("decided_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "publications", "users", ["decided_by"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "publications", type_="foreignkey")
    op.drop_column("publications", "decided_by")
    op.drop_column("publications", "decision_at")
    op.drop_column("publications", "editor_note")
    # ### end Alembic commands ###
