"""add publication tables

Revision ID: 29741e88fe0a
Revises: 3099c02dfc50
Create Date: 2026-07-16 11:57:59.098110

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "29741e88fe0a"
down_revision: str | None = "3099c02dfc50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publications",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column(
            "publication_type",
            sa.Enum(
                "JOURNAL",
                "CONFERENCE",
                "BOOK",
                "PATENT",
                "TECHNICAL_REPORT",
                name="publication_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "REVISION_REQUIRED",
                "ACCEPTED",
                "REJECTED",
                "PUBLISHED",
                "ARCHIVED",
                name="publication_status",
            ),
            nullable=False,
        ),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("pdf_url", sa.String(length=1000), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_table(
        "publication_authors",
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("researcher_id", sa.UUID(), nullable=False),
        sa.Column("author_order", sa.Integer(), nullable=False),
        sa.Column("is_corresponding_author", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["publication_id"], ["publications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["researcher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_authors")
    op.drop_table("publications")
    # ### end Alembic commands ###
