"""add pdf_public_id to publications

Revision ID: 298cdc01894f
Revises: 29741e88fe0a
Create Date: 2026-07-16 13:37:35.402411

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "298cdc01894f"
down_revision: str | None = "29741e88fe0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publications", sa.Column("pdf_public_id", sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publications", "pdf_public_id")
    # ### end Alembic commands ###
