"""add publication chunks

Revision ID: 8f8949b3ae02
Revises: be2e901ee087
Create Date: 2026-08-16 07:30:02.434267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector


# revision identifiers, used by Alembic.
revision: str = "8f8949b3ae02"
down_revision: str | None = "be2e901ee087"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication_chunks",
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["publication_id"], ["publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_publication_chunks_publication_id"),
        "publication_chunks",
        ["publication_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publication_chunks_publication_id"), table_name="publication_chunks")
    op.drop_table("publication_chunks")
    # ### end Alembic commands ###
