"""make publication chunk embedding nullable

Revision ID: afec994eec79
Revises: 8f8949b3ae02
Create Date: 2026-08-16 07:45:20.773710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector


# revision identifiers, used by Alembic.
revision: str = "afec994eec79"
down_revision: str | None = "8f8949b3ae02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publication_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publication_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=False,
    )
    # ### end Alembic commands ###
