"""add institution_id to publications

Revision ID: ceff6e8970fe
Revises: 9fb12a3cb07f
Create Date: 2026-07-18 07:59:37.582818

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ceff6e8970fe"
down_revision: str | None = "9fb12a3cb07f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publications", sa.Column("institution_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "publications", "institutions", ["institution_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "publications", type_="foreignkey")
    op.drop_column("publications", "institution_id")
    # ### end Alembic commands ###
