"""create citations table

Revision ID: 5fc957b675ca
Revises: c493fb40b00f
Create Date: 2026-08-01 21:36:46.007014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc957b675ca'
down_revision: Union[str, Sequence[str], None] = 'c493fb40b00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('citing_title', sa.String(), nullable=False),
    sa.Column('citing_authors', sa.String(), nullable=False),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('citation_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.alter_column('publications', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('citations')
    # ### end Alembic commands ###
