"""add notifications table

Revision ID: 893a0c6dc859
Revises: 5fc957b675ca
Create Date: 2026-08-03 12:01:04.128152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '893a0c6dc859'
down_revision: Union[str, Sequence[str], None] = '5fc957b675ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('notification_type', sa.Enum('COLLABORATION', 'CONFERENCE', 'PUBLICATION', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('publication_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('citing_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('citing_authors', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('journal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('citation_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('citations_publication_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('citations_pkey')),
    sa.UniqueConstraint('doi', name=op.f('citations_doi_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('notifications')
    # ### end Alembic commands ###
