"""Add email verification

Revision ID: c493fb40b00f
Revises: b7e7b16bcfea
Create Date: 2026-07-26 08:59:13.420710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c493fb40b00f'
down_revision: Union[str, Sequence[str], None] = 'b7e7b16bcfea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users",sa.Column("email_verified",sa.Boolean(),nullable=False,server_default=sa.text("false"),),)
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expiry')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'verification_token_expiry')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
