"""Create institution table

Revision ID: fad06445c2d6
Revises: 38bb26482b52
Create Date: 2026-07-09 21:40:08.824842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad06445c2d6'
down_revision: Union[str, Sequence[str], None] = '38bb26482b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('abbreviation', sa.String(length=50), nullable=True))
    op.add_column('institutions', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('institutions', sa.Column('address', sa.String(length=500), nullable=True))
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('institutions', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('institutions', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('institutions', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('institutions', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('institutions', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('institutions', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('institutions', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('institutions', 'address')
    op.drop_column('institutions', 'phone')
    op.drop_column('institutions', 'abbreviation')
    # ### end Alembic commands ###
