"""recreate researcher schema

Revision ID: fecc1ecc3773
Revises: 238281789a81
Create Date: 2026-07-23 14:14:44.489317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fecc1ecc3773'
down_revision: Union[str, Sequence[str], None] = '238281789a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Researchers table already exists, so DO NOT create it again.

    

    

    op.alter_column(
        'publications',
        'citation_count',
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text('0')
    )

    op.alter_column(
        'publications',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()')
    )

    op.alter_column(
        'publications',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()')
    )

    op.drop_constraint(
        op.f('publications_doi_key'),
        'publications',
        type_='unique'
    )

    op.create_unique_constraint(
        'uq_publication_doi',
        'publications',
        ['doi']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_publication_doi', 'publications', type_='unique')
    op.create_unique_constraint(op.f('publications_doi_key'), 'publications', ['doi'], postgresql_nulls_not_distinct=False)
    op.alter_column('publications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('publications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('publications', 'citation_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_table('researcher_departments')
    op.drop_table('publication_authors')
    op.drop_table('researchers')
    # ### end Alembic commands ###
