import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Handshake, Pencil, Plus, Trash2 } from "lucide-react";
import { apiClient } from "@/api/client";

export default function Collaborations() {
  const client = useQueryClient();
  const [form, setForm] = useState<{ id?: string; partner_name: string; description: string; status: string } | null>(null);
  const [details, setDetails] = useState<{ partner_name: string; description: string | null; status: string } | null>(null);
  const collaborations = useQuery({ queryKey: ["collaborations"], queryFn: () => apiClient.listCollaborations() });
  const refresh = () => void client.invalidateQueries({ queryKey: ["collaborations"] });
  const save = useMutation({ mutationFn: (element: HTMLFormElement) => { const values = new FormData(element); const data = { partner_name: String(values.get("partner_name")), description: String(values.get("description") || "") || undefined, status: String(values.get("status")) }; return form?.id ? apiClient.updateCollaboration(form.id, data) : apiClient.createCollaboration(data); }, onSuccess: () => { setForm(null); refresh(); } });
  return <div className="space-y-6"><div className="flex items-end justify-between"><div><p className="page-eyebrow">Research network</p><h1 className="page-title">Collaborations</h1></div><button onClick={() => setForm({ partner_name: "", description: "", status: "ACTIVE" })} className="rounded-xl bg-teal-600 px-4 py-2 text-white"><Plus className="inline h-4 w-4" /> Create Collaboration</button></div>{form && <form onSubmit={(e) => { e.preventDefault(); save.mutate(e.currentTarget); }} className="surface-card grid gap-3 rounded-2xl p-5 md:grid-cols-2"><input name="partner_name" required placeholder="Partner institution" defaultValue={form.partner_name} className="rounded-xl border p-3" /><select name="status" defaultValue={form.status} className="rounded-xl border p-3"><option>ACTIVE</option><option>PAUSED</option><option>COMPLETED</option></select><input name="description" placeholder="Description" defaultValue={form.description} className="rounded-xl border p-3 md:col-span-2" /><button className="rounded-xl bg-teal-600 p-3 text-white">Save</button></form>}<section className="surface-card rounded-2xl">{!collaborations.data?.length ? <p className="p-10 text-center text-slate-500">No collaborations yet.</p> : collaborations.data.map((item) => <div key={item.id} className="flex gap-3 border-b p-5"><Handshake className="text-teal-600" /><div className="flex-1"><b>{item.partner_name}</b><p className="text-sm text-slate-500">{item.status}</p></div><button onClick={() => setDetails(item)}><Eye className="text-slate-600" /></button><button onClick={() => setForm({ id: item.id, partner_name: item.partner_name, description: item.description || "", status: item.status })}><Pencil className="text-teal-700" /></button><button onClick={() => apiClient.deleteCollaboration(item.id).then(refresh)}><Trash2 className="text-rose-600" /></button></div>)}</section>{details && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">{details.partner_name}</h2><p className="mt-3 text-sm text-slate-600">{details.description || "No description"}</p><p className="mt-3 text-sm"><b>Status:</b> {details.status}</p><button onClick={() => setDetails(null)} className="mt-5 rounded-xl border px-4 py-2">Close</button></div></div>}</div>;
}
