import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FolderKanban, Pencil, Plus, Trash2, Users } from "lucide-react";
import { apiClient } from "@/api/client";

export default function Projects() {
  const client = useQueryClient();
  const [selected, setSelected] = useState<string | null>(null);
  const [formProject, setFormProject] = useState<{ id?: string; name: string; status: string; start?: string | null; end?: string | null } | null>(null);
  const projects = useQuery({ queryKey: ["projects"], queryFn: () => apiClient.listProjects() });
  const members = useQuery({ queryKey: ["project-members", selected], queryFn: () => apiClient.listProjectAssignments(selected!), enabled: !!selected });
  const refresh = () => void client.invalidateQueries({ queryKey: ["projects"] });
  const save = useMutation({ mutationFn: (form: HTMLFormElement) => { const f = new FormData(form); const data = { name: String(f.get("name")), status: String(f.get("status")), start_date: String(f.get("start")) || null, end_date: String(f.get("end")) || null }; return formProject?.id ? apiClient.updateProject(formProject.id, data) : apiClient.createProject(data); }, onSuccess: () => { setFormProject(null); refresh(); } });
  const assign = useMutation({ mutationFn: (form: HTMLFormElement) => { const f = new FormData(form); return apiClient.assignProjectMember(selected!, { user_id: String(f.get("user_id")), role: String(f.get("role")) }); }, onSuccess: () => void client.invalidateQueries({ queryKey: ["project-members", selected] }) });
  return <div className="space-y-6"><div className="flex items-end justify-between"><div><p className="page-eyebrow">Research delivery</p><h1 className="page-title">Projects</h1></div><button onClick={() => setFormProject({ name: "", status: "ACTIVE" })} className="rounded-xl bg-teal-600 px-4 py-2 text-white"><Plus className="inline h-4 w-4" /> Add Project</button></div>{formProject && <form onSubmit={(e) => { e.preventDefault(); save.mutate(e.currentTarget); }} className="surface-card grid gap-3 rounded-2xl p-5 md:grid-cols-2"><input name="name" required defaultValue={formProject.name} placeholder="Project name" className="rounded-xl border p-3" /><select name="status" defaultValue={formProject.status} className="rounded-xl border p-3"><option>ACTIVE</option><option>ON_HOLD</option><option>COMPLETED</option></select><input name="start" type="date" defaultValue={formProject.start || ""} className="rounded-xl border p-3" /><input name="end" type="date" defaultValue={formProject.end || ""} className="rounded-xl border p-3" /><button className="rounded-xl bg-teal-600 p-3 text-white">Save</button><button type="button" onClick={() => setFormProject(null)} className="rounded-xl border p-3">Cancel</button></form>}<section className="surface-card rounded-2xl">{projects.data?.map((project) => <div key={project.id} className="flex gap-3 border-b p-5"><FolderKanban className="text-teal-600" /><button onClick={() => setSelected(project.id)} className="flex-1 text-left"><b>{project.name}</b><p className="text-sm text-slate-500">{project.status} · {project.start_date || "No start"} — {project.end_date || "No end"}</p></button><button onClick={() => setFormProject({ id: project.id, name: project.name, status: project.status, start: project.start_date, end: project.end_date })}><Pencil className="text-teal-700" /></button><button onClick={() => apiClient.deleteProject(project.id).then(refresh)}><Trash2 className="text-rose-600" /></button></div>)}</section>{selected && <section className="surface-card rounded-2xl p-5"><h2 className="font-semibold"><Users className="inline h-4 w-4" /> Assigned Members</h2><form onSubmit={(e) => { e.preventDefault(); assign.mutate(e.currentTarget); }} className="mt-3 flex flex-wrap gap-2"><input name="user_id" required placeholder="Researcher user ID" className="rounded-lg border p-2" /><input name="role" defaultValue="MEMBER" className="rounded-lg border p-2" /><button className="rounded-lg bg-teal-600 px-3 text-white">Assign</button></form>{members.data?.map((member) => <p key={member.id} className="mt-3 flex justify-between text-sm">{member.user_id} · {member.role}<button onClick={() => apiClient.removeProjectMember(selected, member.user_id).then(() => client.invalidateQueries({ queryKey: ["project-members", selected] }))} className="text-rose-600">Remove</button></p>)}</section>}</div>;
}
