import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, Eye, Pencil, Plus, Trash2 } from "lucide-react";
import { apiClient } from "@/api/client";

export default function Publications() {
  const client = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editing, setEditing] = useState<string | null>(null);
  const publications = useQuery({ queryKey: ["publications"], queryFn: () => apiClient.listPublications() });
  const current = publications.data?.find((publication) => publication.id === selectedId || publication.id === editing);
  const remove = useMutation({ mutationFn: apiClient.deletePublication.bind(apiClient), onSuccess: () => void client.invalidateQueries({ queryKey: ["publications"] }) });
  const update = useMutation({ mutationFn: ({ id, data }: { id: string; data: { title: string; status: string } }) => apiClient.updatePublication(id, data), onSuccess: () => { void client.invalidateQueries({ queryKey: ["publications"] }); setEditing(null); } });
  return <div className="space-y-6"><div><p className="page-eyebrow">Research records</p><h1 className="page-title">Publications</h1><p className="mt-2 text-slate-500">View, edit, and manage your institution’s publications.</p></div><a href="/dashboard/research-management" className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Add Publication</a><section className="surface-card overflow-hidden rounded-2xl">{!publications.data?.length ? <p className="p-10 text-center text-slate-500">No publications yet.</p> : publications.data.map((publication) => <article key={publication.id} className="flex items-center gap-4 border-b border-slate-100 p-5 last:border-0"><BookOpen className="h-5 w-5 text-teal-600" /><div className="min-w-0 flex-1"><h2 className="font-semibold">{publication.title}</h2><p className="text-sm text-slate-500">{publication.publication_type} · {publication.status}</p></div><button onClick={() => setSelectedId(publication.id)} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><Eye className="h-4 w-4" /></button><button onClick={() => setEditing(publication.id)} className="rounded-lg p-2 text-teal-700 hover:bg-teal-50"><Pencil className="h-4 w-4" /></button><button onClick={() => remove.mutate(publication.id)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><Trash2 className="h-4 w-4" /></button></article>)}</section>{selectedId && current && <PublicationDialog title="Publication Details" publication={current} onClose={() => setSelectedId(null)} />}{editing && current && <PublicationDialog title="Edit Publication" publication={current} editing onClose={() => setEditing(null)} onSave={(data) => update.mutate({ id: current.id, data })} />}</div>;
}

function PublicationDialog({ title, publication, editing = false, onClose, onSave }: { title: string; publication: { title: string; abstract: string | null; status: string; doi: string | null; file_url: string | null }; editing?: boolean; onClose: () => void; onSave?: (data: { title: string; status: string }) => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-semibold">{title}</h2>{editing ? <form onSubmit={(event) => { event.preventDefault(); const values = new FormData(event.currentTarget); onSave?.({ title: String(values.get("title")), status: String(values.get("status")) }); }} className="mt-5 space-y-4"><input name="title" defaultValue={publication.title} className="w-full rounded-xl border p-3" /><select name="status" defaultValue={publication.status} className="w-full rounded-xl border p-3"><option>DRAFT</option><option>SUBMITTED</option><option>PUBLISHED</option><option>ARCHIVED</option></select><button className="rounded-xl bg-teal-600 px-4 py-2 text-white">Save</button></form> : <div className="mt-4 space-y-3 text-sm"><p>{publication.abstract || "No abstract provided."}</p><p><b>Status:</b> {publication.status}</p><p><b>DOI:</b> {publication.doi || "Not provided"}</p>{publication.file_url && <a className="font-medium text-teal-700" href={publication.file_url} target="_blank" rel="noreferrer">View PDF</a>}</div>}<button onClick={onClose} className="mt-5 rounded-xl border px-4 py-2 text-sm">Close</button></div></div>; }
